swagger:
  enabled : true
  title : '摸鱼框架'
  description : '摸鱼框架接口文档'
  license : 'Powered By mfish'
  licenseUrl : 'http://www.mfish.com.cn'
  version : '版本号:V1.0'
  termsOfServiceUrl : 'http://www.mfish.com.cn'
  needAuth : true